# Generated by Django 4.0.6 on 2022-07-14 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDName', models.CharField(max_length=100, verbose_name='Product Name')),
                ('PRDDesc', models.TextField(verbose_name='Description')),
                ('PRDPrice', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Price')),
                ('PRDCost', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Cost')),
                ('PRDCreated', models.DateTimeField(verbose_name='created at')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDIMImage', models.ImageField(upload_to='products', verbose_name='Image')),
                ('PRDIMProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
