# Generated by Django 4.0.6 on 2022-07-15 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='PRDIMImage',
            field=models.ImageField(upload_to='products/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='PRDIMProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='product'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATName', models.CharField(max_length=50, verbose_name='Main category')),
                ('CATImage', models.ImageField(upload_to='category/')),
                ('CATDesc', models.TextField()),
                ('CATParent', models.ForeignKey(limit_choices_to={'CATParent__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='sub category')),
            ],
        ),
    ]
