# Generated by Django 4.0.6 on 2022-07-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_catname_alter_category_catparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDCost',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDPrice',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Price'),
        ),
    ]
