# Generated by Django 4.0.6 on 2022-07-15 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_prdcost_alter_product_prdprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ALTProd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product', verbose_name='product')),
                ('ALTProducts', models.ManyToManyField(related_name='Alternative_products', to='product.product', verbose_name='Alternative products')),
            ],
        ),
    ]
