# Generated by Django 4.0.6 on 2022-07-16 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alternative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative',
            name='ALTProd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ALT_product', to='product.product', verbose_name='product'),
        ),
        migrations.CreateModel(
            name='Accsesory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACCSProd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ACC_product', to='product.product', verbose_name='product')),
                ('ACCSProducts', models.ManyToManyField(related_name='Accsesories', to='product.product', verbose_name='Accsesories')),
            ],
        ),
    ]
